infotor/urls.py
from django.conf.urls import url

from . import views

app_name = 'infotor'
urlpatterns = [
#    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<file_id>[0-9]+)/$', views.info, name='info'),
    url(r'^search/', views.search, name='search'),
#    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
#    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

tor/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.views.generic import RedirectView
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^$", TemplateView.as_view(template_name='main.html'), name='home'),
    url(r'^infotor/', include('infotor.urls')),
]

infotor/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    code_category=models.SmallIntegerField(unique=True, db_index=True, primary_key=True, verbose_name='Код категории')
    name_category=models.CharField(max_length=50, verbose_name='Наименование категории')
    load_category=models.BooleanField(default=True, verbose_name='Загружать?')
    def __str__(self):
        return ('0'+str(self.code_category))[-2:]+'. '+self.name_category
    class Meta:
        db_table='category'
        ordering=['code_category']
        verbose_name_plural='Категории' 

class Forum(models.Model):
    code_forum=models.SmallIntegerField(unique=True, db_index=True, primary_key=True, verbose_name='Код форума')
    name_forum=models.CharField(max_length=80, verbose_name='Наименование форума')
    category=models.ForeignKey(Category, default=0, verbose_name='Категория', on_delete=models.SET_DEFAULT, related_name='categorylink')
    def __str__(self):
        return ('0'+str(self.category_id))[-2:]+' - ' + str(self.code_forum)+'. '+self.name_forum    
    class Meta:
        db_table='forum'
        ordering=['category_id','code_forum']
        verbose_name_plural='Форумы'

class Torrents(models.Model):
    #category=models.ForeignKey(Category, default=0, verbose_name='Категория', on_delete=models.SET_DEFAULT)
    forum=models.ForeignKey(Forum, default=0, verbose_name='Форум', on_delete=models.SET_DEFAULT, related_name='forumlink')
    file_id=models.IntegerField(unique=True, db_index=True, primary_key=True, verbose_name='ID файла')
    hash_info=models.CharField(max_length=40, verbose_name='Hash')
    title=models.CharField(max_length=255, verbose_name='Наименование раздачи')
    size_b=models.IntegerField(verbose_name='Размер файла в байтах')
    date_reg=models.CharField(max_length=20, verbose_name='Зарегистрировано')
    class Meta:
        db_table='torrent'
        ordering=['file_id']
        verbose_name_plural='Раздачи'
    def __str__(self):
        return (str(self.file_id) + ' :: ' + self.title)    

class Contents(models.Model):
    tid=models.IntegerField(unique=True, db_index=True, primary_key=True, verbose_name='ID файла')
    cont=models.TextField(verbose_name='Контент')
    class Meta:
        db_table='contents'
        ordering=['tid']
        verbose_name_plural='Контент'

class Vers(models.Model):
    vers=models.CharField(max_length=8, verbose_name='Версия')
    class Meta:
        db_table='vers'
    def __str__(self):
        return self.vers    

infotor/views.py
from django.http import HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404
from .models import Torrents, Category, Forum, Contents, Vers
from django.urls import reverse
from django.views import generic
from django.http import HttpResponse
from zlib import decompress
import infotor.modbbcode as bbc
from django.db.models import Q
from django.core.paginator import Paginator,InvalidPage
import re
from django.db import connections

def outlist(i,p_num):
    shtml=''' <a href="#" onclick="setpar('poz',{});">[ {} ] </a>'''
    if i!=int(p_num):
        pg = shtml.format(str(i),str(i))
    else:
        pg = '<b>[ %s ]</b> ' % str(i)
    return pg        

def squery(fraze='',razdel='0',frm='0'):
    sfq='''SELECT name_category, name_forum, file_id, hash_info, title, size_b, date_reg, code_forum 
    FROM (torrent AS t inner join forum AS f on t.forum_id=f.code_forum) 
    inner join category AS C on f.category_id=C.code_category WHERE size_b>0 '''
    sfq+=splitter(fraze)
    if razdel!='00':
        sfq+=' AND f.category_id=%s ' % (str(int(razdel)),)
    if frm!='0':
        sfq+=' AND f.code_forum=%s ' % (str(int(frm)),)
    sfq+=' ORDER BY f.category_id asc, f.name_forum asc, file_id desc'
    return sfq

def splitter(text=''):
    ssq=''
    for fraza in re.findall(r"[\'\"](.*?)[\'\"]",text):
        text=text.replace(fraza,'')
        if len(fraza)>0: ssq+=' AND lower(title) LIKE "%'+fraza.lower()+'%"'
    for word in re.split(r'\s',text):
        word=re.sub(r'[\"\'\*\+\<\>?]','',word)
        if len(word)>0: ssq+=' AND (lower(title) LIKE "%'+word.lower()+'%" OR title LIKE "%'+word.capitalize()+'%")'
    return ssq

def search(request):
    template_name = 'infotor/search.html'
    result_cat = Category.objects.order_by('code_category')
    vers = Vers.objects.get(pk=1)
    version = 'Версия базы от %s.%s.%s' % (str(vers)[-2:],str(vers)[4:6],str(vers)[:4])
    razd = request.GET.get('category',default='00')
    podr = request.GET.get('podr',default='0')
    querytext = request.GET.get('querytext',default='')
    page_num = request.GET.get('page',default='1')
            
    if querytext!='' or podr!='0':
        mode=1
        sql=squery(querytext,razd,podr)
        paginator = Paginator((list(Torrents.objects.raw(sql))),100)
        countrec = str(paginator.count)
    elif razd!='00':
        mode=2
        paginator=Paginator(Forum.objects.filter(category_id=razd).order_by("name_forum"),200)
        countrec = str(paginator.count)
    elif querytext=='' and razd=='00':
        mode=0
        paginator=Paginator(Torrents.objects.order_by("file_id"),1)
        countrec = str(paginator.count)
    
    if countrec[-1:] == '1' and countrec != '11':
        zap=' запись'
    elif countrec in ('11','12','13','14') or countrec[-1:] in ('0','5','6','7','8','9'):
        zap=' записей'
    else:
        zap=' записи' 
    if page_num=='':
        page_num='1'
    
    pager=''
    if int(countrec)>0:
        smax=((int(countrec)-1)//100)+1
        L = range(0,smax)
        pcur=int(page_num)
        pmin = pcur - 4
        pmax = pcur + 5
        if pmin < 2: 
            pmin = 2
        if pmax > smax: 
            pmax = smax
        pager += outlist(1,page_num)
        if pcur>6: 
            pager += ' ... '
        for j in L[pmin:pmax]:
            pager += outlist(j,page_num)
        if pcur < smax-5: 
            pager += ' ... '
        if smax!=1: 
            pager += outlist(smax,page_num)
    
    return render(request, template_name, {
        "category": result_cat,
        "sel_category": int(razd), 
        "forum":podr,
        "vers":version,
        "querytext":querytext,
        "result":paginator.page(page_num),
        "pozlist":(int(page_num)-1)*100,
        "countrec":countrec+zap,
        "mode":mode,
        "pager":pager,
       })

def info(request,file_id):
    template_name = 'infotor/info.html'
    try:
        result=Torrents.objects.all().get(pk=file_id)
    except (KeyError, Torrents.DoesNotExist):
        result=None

    try:
        cont=Contents.objects.get(tid=file_id)       
        if cont:
            S=decompress(cont.cont)
            result2 = bbc.bbcode2html(S.decode('utf-8'))

    except (KeyError, Contents.DoesNotExist):
        result2 = ":("

    return render(request, template_name, {"result": result,"result2": result2})


infotor/templates/infotor/base.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8">
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% static 'infotor.css' %}" />
<link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>
</head><body>
{% block javascript %}{% endblock %}
{% block header %}{% endblock %}

{% block main %}{% endblock %}

<div class="layer4" >
<table class="subtable" cellpadding="0" cellspacing="0">
<tr>
{% block footer %}{% endblock %}
<td align="right"><p>&copy; Y3401</p></td>
</tr></table></div>
{% block menu %}{% endblock %}
</body></html>

infotor/templates/infotor/info.html
{% extends "infotor/base.html" %}
{% load staticfiles %}

{% block title %}{{ result.title }}{% endblock %}

{% block javascript %}
<script language="JavaScript" type="text/javascript">
    function showBlock(t) {
           var elStyle = document.getElementById( t ).style;
           elStyle.display = (elStyle.display == 'none') ? '' : 'none'}
</script>
{% endblock %}

{% block header %}
<div class="layer6">
{% if result %}
<table class="subtable"><tr>
<td style="vertical-align:top;"><p class="info">{{ result.forum.category.name_category }}<br />&rArr; {{ result.forum.name_forum }}</p></td>
<td style="width: 18%; vertical-align:middle"><p class="info">Размер: <span title="Точный размер: {{ result.size_b }}" style="cursor: help"><b>{{ result.size_b|filesizeformat  }}</b></span></p></td>
<td style="width: 25%; vertical-align:middle" align="right"><p class="info"><b>{{ result.date_reg }}</b></p></td>
<td style="width: 7%;"><a href="magnet:?xt=urn:btih:{{ result.hash_info }}"><img src="{% static 'images/download40.png' %}" align="right" alt="Скачать" title="Скачать по magnet-ссылке"></a></td></tr></table></div>
<div class="layer5"><h2>{{ result.title }}</h2></div>
{% else %}
<div class="layer5"><h2>Запись отсутствует</h2></div>
{% endif %}
{% endblock %}

{% block main %}
<div class="layer3" style="position: fixed;  top:130px; background-color: rgb(227,227,227);">
<div class="post_body">
{{ result2|safe }}
</div></div>
{% endblock %}

{% block footer %}
<td width="20%"><p>...</p></td>
<td width="60%" align="center"><p>...</p></td>
{% endblock %}

{% block menu %}
<div class="clo"><a class="cl1" href="javascript:window.close()" title="Закрыть"></a></div>
{% endblock %}

infotor/templates/infotor/search.html
{% extends "infotor/base.html" %}
{% load staticfiles %}
{% block title %}Категории{% endblock %}

{% block javascript %}
{% verbatim %}
<script language="JavaScript" type="text/javascript">
function setpar(pole,param) {
    document.getElementById(pole).value = param;
    document.form1.Submit1.click();}
</script>
{% endverbatim %}
{% endblock %}

{% block header %}
<div class="layer2">
<form method="get" action="" name="form1">
	<fieldset name="Group1">
	<legend>Параметры поиска</legend>
		<input name="querytext" type="text" placeholder="Введите ключевые слова" value="{{ querytext }}" onchange='document.getElementById("poz").value ="1";' style="width: 63%; height: 20; margin-right: 10px; top: 15px; vertical-align: text-bottom word-spacing: 5; float: left; cursor: text; display: inline;">
		<select name="category" onchange='document.getElementById("poz").value ="1";document.getElementById("podr").value ="0";' style="width: 200px; position:static; height: 20px; top: 15px; vertical-align: text-bottom">
<option value="00">...</option>
{% if category %}
    {% for cate in category %}
        {% if sel_category == cate.code_category %}
            <option selected value="{{ cate.code_category }}">{{ cate.name_category }}</option>
        {% else %} 
            <option value="{{ cate.code_category }}">{{ cate.name_category }}</option>
        {% endif %}
    {% endfor %}
{% endif %}

</select><input name="Submit1" type="submit" id="submit" value="Поиск" style="position: relative; float:right;vertical-align: text-bottom;">
<input name="page" type="hidden" id="poz" value="1">
<input name="podr" type="hidden" id="podr" value="{{ forum }}"></fieldset></form></div>
{% endblock %}

{% block main %}
<div class="layer3">
{% if mode == 1 %}
    {% if result %}
       {% for item in result %}
<table align="center" cellpadding="2" cellspacing="1" class="maintable">
    <tr><td class="cell-1"><p><center>{{ forloop.counter|add:pozlist }}</center></p></td>
        <td class="td-style4"><table class="subtable" cellpadding="0" cellspacing="0">
    <tr><td class="cell-l">{{ item.forum.category.name_category }} - <a href="#" onclick="setpar('podr',{{item.forum_id}})">{{ item.forum.name_forum }}</a></td>
        <td class="cell-r">Зарегистрировано: <b>{{ item.date_reg }}</b></td></tr>
    <tr><td colspan="2" class="cell-title"><a href="#" ONCLICK="window.open('{% url "infotor:info" item.file_id %}','');return false;"><b>{{ item.title }}</b></a></td></tr>
    <tr><td class="cell-l">Размер: <span title="Точный размер: {{ item.size_b }}" style="cursor: help"><b>{{ item.size_b|filesizeformat }}</b></span></td>
        <td class="cell-r"><span id="hsh0">{{ item.hash_info }}</span></td></tr></table></td>
        <td class="cell-2"><a href="magnet:?xt=urn:btih:{{ item.hash_info }}"><img alt="Скачать" longdesc="Скачать по magnet-ссылке" src="{% static 'images/download40.png' %}"></td></tr>
</table>    
        {% endfor %}
    {% endif %}
{% elif mode == 2 %}
    <ul>
    {% for item in result %}
        <li class="menu"><a href="#" onclick="setpar('podr',{{ item.code_forum }});">{{ item.name_forum }} </a></li>
    {% endfor %}
    </ul>
{% elif mode == 0%}
    <center><table>
    <tr width="800px" vertical-align="middle" ><td width="20%"></td><td height="300px" align="left">
    <p>Для поиска по локальной базе данных <b>InfoTor</b> введите ключевые фразы
    или слова и/или выберите вначале категорию, затем подраздел,
    а затем поисковые фразы или слова.</p>
    <p>Фразы выделяются двойными() или одиночными() кавычками. Между фразами и словами и между слов разделитель - пробел</p>
    <p>Например:</p> <p><pre class="ppre">&quot;Особенности национальной&quot; 'зимний период' комедия</pre></p>
    <p>Предпочтительнее использовать ключевые слова.</p>
    <p>Фразы используйте в том случае, если уверены в написании регистра букв фразы на русском языке (из-за отсутствия модуля ICU поисковый запрос чувствителен к регистру русских букв. Для латиницы же можно вводить как строчными, так и прописными буквами.)<p> 
    </td><td width="20%"></td></tr></table></center>
    {% endif %}

{% endblock %}

{% block footer %}
<td width="30%"><p>Найдено {{ countrec }} </p></td>
<td width="40%" style="text-align:center"><p>
{% if mode == 1 %}
{{ pager|safe }}
{% elif mode == 2 %}
{{vers}}
{% elif mode == 0 %}
{{vers}}
{% endif %}
</p></td>
{% endblock %}

{% block menu %}
<div class="home"><a class="cl1" href="{% url 'home' %}" title="На главную страницу"></a></div>
<div class="back"><a class="cl1" href="javascript:history.back()" title="Назад"></a></div>
{% endblock %}

templates/main.html
<!DOCTYPE html>
<html><head>
<meta http-equiv="content-type" content="text/html; charset=utf-8">
<title>Локальная поисковая система InfoTor</title>
<link rel="stylesheet" type="text/css" href="../static/infotor.css" />
</head>
<body>
<div class="layer1"><h1>Локальная поисковая система InfoTor</h1></div>
<div class="layer3">

	<table style="width: 100%; height:80%">
		<tr>
			<td style="width:30%">&nbsp;</td>
			<td style="vertical-align:middle;">
				<li class="but"><a href="infotor/search">Поехали..</a></li>
			</td>
			<td style="width:30%">&nbsp;</td>
		</tr>
	</table>
<br />
</div>	

<div class="layer4" >
<table class="subtable" cellpadding="0" cellspacing="0">
<tr><td width="30%"></td>
<td width="40%" style="text-align:center"><p>- 2017 -</p></td>
<td align="right"><p>&copy; Y3401</p></td>
</tr></table></div>
</body></html>